name: Python Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Choose the Python version you want to use, e.g., 3.8, 3.9, etc.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements for your project

      - name: Run unit tests
        run: |
          python -m unittest discover -v

    # Add additional steps as needed, such as code coverage, linting, etc.

# name: Test Branch CI

# on:
#   push:
#     branches:
#       - test
#   pull_request:
#     branches:
#       - test

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run unit tests
#         run: |
#           python -m unittest discover -v

#   create_pull_request:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           commit-message: Automated pull request to merge dev into test
#           title: Automated pull request to merge dev into test
#           body: |
#             This is an automated pull request to merge dev into test.
#             It was triggered by a successful build on the dev branch.
#           branch: test
#           base: dev
